# Generated by Django 4.1.2 on 2022-11-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaoo', '0004_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='profile_photo/%Y/'),
        ),
    ]
